openapi: 3.0.0
info:
  title: Reminders Backend API
  description: Backend service for the Reminders frontend.
  version: "1.0"
servers:
  - url: http://localhost:8080
    description: Development server
paths:
  /create-reminder:
    post:
      summary: Create a reminder
      description: Forwards the reminder creation request to the Reminder service with proper authentication.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReminderRequest'
      responses:
        '200':
          description: Reminder created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReminderResponse'
        '401':
          description: Authentication failed
        '500':
          description: Internal server error
  /reminders:
    get:
      summary: Get reminder by email
      description: Fetches reminders for the given email. Supports filtering by the 'upcoming' query parameter.
      parameters:
        - in: query
          name: email
          schema:
            type: string
            format: email
          required: true
          description: Email address to filter reminders
        - in: query
          name: upcoming
          schema:
            type: string
            enum: ['true', 'false']
          required: false
          description: Optional filter for fetching only upcoming reminders
      responses:
        '200':
          description: A list of reminders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReminderResponse'
        '400':
          description: Missing or invalid parameters
        '401':
          description: Authentication failed
        '500':
          description: Internal server error
components:
  schemas:
    ReminderRequest:
      type: object
      properties:
        name:
          type: string
          example: John Doe
        description:
          type: string
          example: Assingnment Deadline
        phoneNumber:
          type: string
          example: '+1234567890'
        reminderDate:
          type: string
          format: date-time
          example: '2023-04-30T14:00:00Z'
        email:
          type: string
          format: email
          example: john.doe@example.com
      required:
        - name
        - description
        - phoneNumber
        - reminderDate
        - email
    ReminderResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: John Doe
        description:
          type: string
          example: Dental Checkup
        phoneNumber:
          type: string
          example: '+1234567890'
        reminderDate:
          type: string
          format: date-time
          example: '2023-04-30T14:00:00Z'
        email:
          type: string
          format: email
          example: firstname.surname@example.com
        status:
          type: string
          example: Pending
      required:
        - id
        - name
        - description
        - phoneNumber
        - reminderDate
        - email
        - status
